AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Bundler/OrderedGems:
  AutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - 'test/**/*.rb'
    - "spec/**/*"
    - "link_community.gemspec"

Metrics/MethodLength:
  Max: 100
